version: "3"
services:
  server:
    build:
      context: .
    command: npm start
    ports:
      - 4000:4000
    environment:
      - SECRET=secret
      - POSTGRES_HOST=attendance.colhqgfesfgd.us-east-2.rds.amazonaws.com
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=9RVNiAK6446Ahs
      - POSTGRES_DATABASE=testdb
